// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#include "../ui.h"

void ui_ScreenRegister_screen_init(void)
{
    ui_ScreenRegister = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenRegister, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelReg = lv_obj_create(ui_ScreenRegister);
    lv_obj_set_width(ui_PanelReg, 300);
    lv_obj_set_height(ui_PanelReg, 300);
    lv_obj_set_align(ui_PanelReg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelReg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RegUser = lv_textarea_create(ui_PanelReg);
    lv_obj_set_width(ui_RegUser, 150);
    lv_obj_set_height(ui_RegUser, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_RegUser, 0);
    lv_obj_set_y(ui_RegUser, -40);
    lv_obj_set_align(ui_RegUser, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_RegUser, "Username");
    lv_textarea_set_one_line(ui_RegUser, true);



    ui_RegPass = lv_textarea_create(ui_PanelReg);
    lv_obj_set_width(ui_RegPass, 150);
    lv_obj_set_height(ui_RegPass, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_RegPass, 0);
    lv_obj_set_y(ui_RegPass, 10);
    lv_obj_set_align(ui_RegPass, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_RegPass, "Password");
    lv_textarea_set_one_line(ui_RegPass, true);
    lv_textarea_set_password_mode(ui_RegPass, true);



    ui_BtnSubmitReg = lv_btn_create(ui_PanelReg);
    lv_obj_set_width(ui_BtnSubmitReg, 150);
    lv_obj_set_height(ui_BtnSubmitReg, 40);
    lv_obj_set_x(ui_BtnSubmitReg, 0);
    lv_obj_set_y(ui_BtnSubmitReg, 110);
    lv_obj_set_align(ui_BtnSubmitReg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSubmitReg, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSubmitReg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_BtnSubmitReg);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Register Now");

    ui_RegPassConfirm = lv_textarea_create(ui_PanelReg);
    lv_obj_set_width(ui_RegPassConfirm, 150);
    lv_obj_set_height(ui_RegPassConfirm, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_RegPassConfirm, 0);
    lv_obj_set_y(ui_RegPassConfirm, 60);
    lv_obj_set_align(ui_RegPassConfirm, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_RegPassConfirm, "Confirm");
    lv_textarea_set_one_line(ui_RegPassConfirm, true);
    lv_textarea_set_password_mode(ui_RegPassConfirm, true);



    ui_Label5 = lv_label_create(ui_PanelReg);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 30);
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "Please iuput your infomation");

    ui_Button1 = lv_btn_create(ui_ScreenRegister);
    lv_obj_set_width(ui_Button1, 60);
    lv_obj_set_height(ui_Button1, 30);
    lv_obj_set_x(ui_Button1, -20);
    lv_obj_set_y(ui_Button1, -20);
    lv_obj_set_align(ui_Button1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Back");

    ui_KeyboardReg = lv_keyboard_create(ui_ScreenRegister);
    lv_obj_set_width(ui_KeyboardReg, 300);
    lv_obj_set_height(ui_KeyboardReg, 120);
    lv_obj_set_x(ui_KeyboardReg, 0);
    lv_obj_set_y(ui_KeyboardReg, 176);
    lv_obj_set_align(ui_KeyboardReg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardReg, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_RegUser, ui_event_RegUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RegPass, ui_event_RegPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSubmitReg, ui_event_BtnSubmitReg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RegPassConfirm, ui_event_RegPassConfirm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelReg, ui_event_PanelReg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenRegister, ui_event_ScreenRegister, LV_EVENT_ALL, NULL);

}
