// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#include "../ui.h"

void ui_ScreenGame_screen_init(void)
{
    ui_ScreenGame = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenGame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelGameInfo = lv_label_create(ui_ScreenGame);
    lv_obj_set_width(ui_LabelGameInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGameInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGameInfo, -283);
    lv_obj_set_y(ui_LabelGameInfo, -202);
    lv_obj_set_align(ui_LabelGameInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGameInfo, "Waiting for opponent...");

    ui_PanelBoard = lv_obj_create(ui_ScreenGame);
    lv_obj_set_width(ui_PanelBoard, 360);
    lv_obj_set_height(ui_PanelBoard, 400);
    lv_obj_set_align(ui_PanelBoard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelBoard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBoard, lv_color_hex(0xDEB887), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBoard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnExitGame = lv_btn_create(ui_ScreenGame);
    lv_obj_set_width(ui_BtnExitGame, 60);
    lv_obj_set_height(ui_BtnExitGame, 30);
    lv_obj_set_x(ui_BtnExitGame, -20);
    lv_obj_set_y(ui_BtnExitGame, -20);
    lv_obj_set_align(ui_BtnExitGame, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnExitGame, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnExitGame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_BtnExitGame);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Back");

    lv_obj_add_event_cb(ui_BtnExitGame, ui_event_BtnExitGame, LV_EVENT_ALL, NULL);

}
