// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#include "../ui.h"

void ui_ScreenLogin1_screen_init(void)
{
    ui_ScreenLogin1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLogin1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardRes = lv_keyboard_create(ui_ScreenLogin1);
    lv_obj_set_width(ui_KeyboardRes, 425);
    lv_obj_set_height(ui_KeyboardRes, 180);
    lv_obj_set_x(ui_KeyboardRes, -160);
    lv_obj_set_y(ui_KeyboardRes, 0);
    lv_obj_set_align(ui_KeyboardRes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardRes, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_PanelLogin1 = lv_obj_create(ui_ScreenLogin1);
    lv_obj_set_width(ui_PanelLogin1, 300);
    lv_obj_set_height(ui_PanelLogin1, 300);
    lv_obj_set_align(ui_PanelLogin1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLogin1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InputUser1 = lv_textarea_create(ui_PanelLogin1);
    lv_obj_set_width(ui_InputUser1, 150);
    lv_obj_set_height(ui_InputUser1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_InputUser1, 0);
    lv_obj_set_y(ui_InputUser1, -40);
    lv_obj_set_align(ui_InputUser1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_InputUser1, "Username");
    lv_textarea_set_one_line(ui_InputUser1, true);



    ui_InputPass1 = lv_textarea_create(ui_PanelLogin1);
    lv_obj_set_width(ui_InputPass1, 150);
    lv_obj_set_height(ui_InputPass1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_InputPass1, 0);
    lv_obj_set_y(ui_InputPass1, 10);
    lv_obj_set_align(ui_InputPass1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_InputPass1, "Password");
    lv_textarea_set_one_line(ui_InputPass1, true);
    lv_textarea_set_password_mode(ui_InputPass1, true);



    ui_BtnRegister1 = lv_btn_create(ui_PanelLogin1);
    lv_obj_set_width(ui_BtnRegister1, 150);
    lv_obj_set_height(ui_BtnRegister1, 40);
    lv_obj_set_x(ui_BtnRegister1, 0);
    lv_obj_set_y(ui_BtnRegister1, 60);
    lv_obj_set_align(ui_BtnRegister1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnRegister1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnRegister1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_BtnRegister1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Register");

    lv_obj_add_event_cb(ui_InputUser1, ui_event_InputUser1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InputPass1, ui_event_InputPass1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnRegister1, ui_event_BtnRegister1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenLogin1, ui_event_ScreenLogin1, LV_EVENT_ALL, NULL);

}
