// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#include "../ui.h"

void ui_ScreenRoom_screen_init(void)
{
    ui_ScreenRoom = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenRoom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelRoomTitle = lv_label_create(ui_ScreenRoom);
    lv_obj_set_width(ui_LabelRoomTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRoomTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRoomTitle, -333);
    lv_obj_set_y(ui_LabelRoomTitle, -196);
    lv_obj_set_align(ui_LabelRoomTitle, LV_ALIGN_CENTER);

    ui_PanelP1 = lv_obj_create(ui_ScreenRoom);
    lv_obj_set_width(ui_PanelP1, 250);
    lv_obj_set_height(ui_PanelP1, 50);
    lv_obj_set_align(ui_PanelP1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelP1Name = lv_label_create(ui_PanelP1);
    lv_obj_set_width(ui_LabelP1Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelP1Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelP1Name, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelP1Name, "Me");

    ui_LabelP1Status = lv_label_create(ui_PanelP1);
    lv_obj_set_width(ui_LabelP1Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelP1Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelP1Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelP1Status, "Not Ready");
    lv_obj_set_style_text_color(ui_LabelP1Status, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelP1Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelP2 = lv_obj_create(ui_ScreenRoom);
    lv_obj_set_width(ui_PanelP2, 240);
    lv_obj_set_height(ui_PanelP2, 50);
    lv_obj_set_x(ui_PanelP2, 2);
    lv_obj_set_y(ui_PanelP2, 75);
    lv_obj_set_align(ui_PanelP2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelP2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelP2Name = lv_label_create(ui_PanelP2);
    lv_obj_set_width(ui_LabelP2Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelP2Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelP2Name, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelP2Name, "waitng");

    ui_LabelP2Status = lv_label_create(ui_PanelP2);
    lv_obj_set_width(ui_LabelP2Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelP2Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelP2Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelP2Status, "Not Ready");
    lv_obj_set_style_text_color(ui_LabelP2Status, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelP2Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnReady = lv_btn_create(ui_ScreenRoom);
    lv_obj_set_width(ui_BtnReady, 100);
    lv_obj_set_height(ui_BtnReady, 50);
    lv_obj_set_x(ui_BtnReady, 248);
    lv_obj_set_y(ui_BtnReady, -32);
    lv_obj_set_align(ui_BtnReady, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnReady, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnReady, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_BtnReady);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "ready");

    ui_BtnLeave = lv_btn_create(ui_ScreenRoom);
    lv_obj_set_width(ui_BtnLeave, 100);
    lv_obj_set_height(ui_BtnLeave, 50);
    lv_obj_set_x(ui_BtnLeave, 252);
    lv_obj_set_y(ui_BtnLeave, 96);
    lv_obj_set_align(ui_BtnLeave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnLeave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLeave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_BtnLeave);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "leave");

    lv_obj_add_event_cb(ui_BtnReady, ui_event_BtnReady, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnLeave, ui_event_BtnLeave, LV_EVENT_ALL, NULL);

}
