// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#include "../ui.h"

void ui_ScreenLobby_screen_init(void)
{
    ui_ScreenLobby = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLobby, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_ScreenLobby);
    lv_obj_set_width(ui_Button3, 60);
    lv_obj_set_height(ui_Button3, 30);
    lv_obj_set_x(ui_Button3, -20);
    lv_obj_set_y(ui_Button3, -20);
    lv_obj_set_align(ui_Button3, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Logout");

    lv_obj_add_event_cb(ui_Label14, ui_event_Label14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
