// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#include "../ui.h"

void ui_ScreenLogin_screen_init(void)
{
    ui_ScreenLogin = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardLogin = lv_keyboard_create(ui_ScreenLogin);
    lv_obj_set_width(ui_KeyboardLogin, 425);
    lv_obj_set_height(ui_KeyboardLogin, 180);
    lv_obj_set_x(ui_KeyboardLogin, -160);
    lv_obj_set_y(ui_KeyboardLogin, 0);
    lv_obj_set_align(ui_KeyboardLogin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardLogin, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_PanelLogin = lv_obj_create(ui_ScreenLogin);
    lv_obj_set_width(ui_PanelLogin, 300);
    lv_obj_set_height(ui_PanelLogin, 300);
    lv_obj_set_x(ui_PanelLogin, -30);
    lv_obj_set_y(ui_PanelLogin, 0);
    lv_obj_set_align(ui_PanelLogin, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_PanelLogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InputUser = lv_textarea_create(ui_PanelLogin);
    lv_obj_set_width(ui_InputUser, 150);
    lv_obj_set_height(ui_InputUser, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_InputUser, 0);
    lv_obj_set_y(ui_InputUser, -40);
    lv_obj_set_align(ui_InputUser, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_InputUser, "Username");
    lv_textarea_set_one_line(ui_InputUser, true);



    ui_InputPass = lv_textarea_create(ui_PanelLogin);
    lv_obj_set_width(ui_InputPass, 150);
    lv_obj_set_height(ui_InputPass, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_InputPass, 0);
    lv_obj_set_y(ui_InputPass, 10);
    lv_obj_set_align(ui_InputPass, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_InputPass, "Password");
    lv_textarea_set_one_line(ui_InputPass, true);
    lv_textarea_set_password_mode(ui_InputPass, true);



    ui_BtnLogin = lv_btn_create(ui_PanelLogin);
    lv_obj_set_width(ui_BtnLogin, 150);
    lv_obj_set_height(ui_BtnLogin, 40);
    lv_obj_set_x(ui_BtnLogin, 0);
    lv_obj_set_y(ui_BtnLogin, 60);
    lv_obj_set_align(ui_BtnLogin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnLogin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_BtnLogin);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Login");

    ui_BtnToRegister1 = lv_btn_create(ui_PanelLogin);
    lv_obj_set_width(ui_BtnToRegister1, 150);
    lv_obj_set_height(ui_BtnToRegister1, 40);
    lv_obj_set_x(ui_BtnToRegister1, 0);
    lv_obj_set_y(ui_BtnToRegister1, 110);
    lv_obj_set_align(ui_BtnToRegister1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnToRegister1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnToRegister1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_BtnToRegister1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Go Register");

    ui_Label2 = lv_label_create(ui_PanelLogin);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 30);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "welcome chess match system");

    lv_obj_add_event_cb(ui_InputUser, ui_event_InputUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InputPass, ui_event_InputPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnLogin, ui_event_BtnLogin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnToRegister1, ui_event_BtnToRegister1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenLogin, ui_event_ScreenLogin, LV_EVENT_ALL, NULL);

}
