// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#include "../ui.h"

void ui_ScreenLogin_screen_init(void)
{
    ui_ScreenLogin = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLogin, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags

    ui_KeyboardLogin = lv_keyboard_create(ui_ScreenLogin);
    lv_obj_set_width(ui_KeyboardLogin, 425);
    lv_obj_set_height(ui_KeyboardLogin, 180);
    lv_obj_set_x(ui_KeyboardLogin, -160);
    lv_obj_set_y(ui_KeyboardLogin, 0);
    lv_obj_set_align(ui_KeyboardLogin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardLogin, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_PanelLogin = lv_obj_create(ui_ScreenLogin);
    lv_obj_set_width(ui_PanelLogin, 300);
    lv_obj_set_height(ui_PanelLogin, 300);
    lv_obj_set_x(ui_PanelLogin, -30);
    lv_obj_set_y(ui_PanelLogin, 0);
    lv_obj_set_align(ui_PanelLogin, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_PanelLogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InputUser = lv_textarea_create(ui_PanelLogin);
    lv_obj_set_width(ui_InputUser, 150);
    lv_obj_set_height(ui_InputUser, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_InputUser, 0);
    lv_obj_set_y(ui_InputUser, -40);
    lv_obj_set_align(ui_InputUser, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_InputUser, "Username");
    lv_textarea_set_one_line(ui_InputUser, true);



    ui_InputPass = lv_textarea_create(ui_PanelLogin);
    lv_obj_set_width(ui_InputPass, 150);
    lv_obj_set_height(ui_InputPass, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_InputPass, 0);
    lv_obj_set_y(ui_InputPass, 10);
    lv_obj_set_align(ui_InputPass, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_InputPass, "Password");
    lv_textarea_set_one_line(ui_InputPass, true);
    lv_textarea_set_password_mode(ui_InputPass, true);



    ui_BtnLogin = lv_btn_create(ui_PanelLogin);
    lv_obj_set_width(ui_BtnLogin, 150);
    lv_obj_set_height(ui_BtnLogin, 40);
    lv_obj_set_x(ui_BtnLogin, 0);
    lv_obj_set_y(ui_BtnLogin, 60);
    lv_obj_set_align(ui_BtnLogin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnLogin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_BtnLogin);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Login");

    ui_BtnToRegister1 = lv_btn_create(ui_PanelLogin);
    lv_obj_set_width(ui_BtnToRegister1, 150);
    lv_obj_set_height(ui_BtnToRegister1, 40);
    lv_obj_set_x(ui_BtnToRegister1, 0);
    lv_obj_set_y(ui_BtnToRegister1, 110);
    lv_obj_set_align(ui_BtnToRegister1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnToRegister1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnToRegister1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_BtnToRegister1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Go Register");

    ui_Label2 = lv_label_create(ui_PanelLogin);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 30);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "welcome chess match system");

    ui_PanelLoginSuccess = lv_obj_create(ui_ScreenLogin);
    lv_obj_set_width(ui_PanelLoginSuccess, 800);
    lv_obj_set_height(ui_PanelLoginSuccess, 480);
    lv_obj_set_align(ui_PanelLoginSuccess, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelLoginSuccess, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelLoginSuccess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLoginSuccess, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLoginSuccess, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_PanelLoginSuccess);
    lv_obj_set_width(ui_Panel2, 240);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Login success! Goto menu...");

    ui_PanelLoginFail = lv_obj_create(ui_ScreenLogin);
    lv_obj_set_width(ui_PanelLoginFail, 800);
    lv_obj_set_height(ui_PanelLoginFail, 480);
    lv_obj_set_align(ui_PanelLoginFail, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelLoginFail, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelLoginFail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLoginFail, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLoginFail, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_PanelLoginFail);
    lv_obj_set_width(ui_Panel3, 420);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Login fail! please check your username or password.");

    ui_PanelLoginRepeat = lv_obj_create(ui_ScreenLogin);
    lv_obj_set_width(ui_PanelLoginRepeat, 800);
    lv_obj_set_height(ui_PanelLoginRepeat, 480);
    lv_obj_set_align(ui_PanelLoginRepeat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelLoginRepeat, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelLoginRepeat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLoginRepeat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLoginRepeat, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_PanelLoginRepeat);
    lv_obj_set_width(ui_Panel4, 280);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Login fail! You can not login repeat!");

    lv_obj_add_event_cb(ui_InputUser, ui_event_InputUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InputPass, ui_event_InputPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnLogin, ui_event_BtnLogin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnToRegister1, ui_event_BtnToRegister1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelLogin, ui_event_PanelLogin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenLogin, ui_event_ScreenLogin, LV_EVENT_ALL, NULL);

}
