// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenLogin
void ui_ScreenLogin_screen_init(void);
void ui_event_ScreenLogin(lv_event_t * e);
lv_obj_t * ui_ScreenLogin;
lv_obj_t * ui_KeyboardLogin;
void ui_event_PanelLogin(lv_event_t * e);
lv_obj_t * ui_PanelLogin;
void ui_event_InputUser(lv_event_t * e);
lv_obj_t * ui_InputUser;
void ui_event_InputPass(lv_event_t * e);
lv_obj_t * ui_InputPass;
void ui_event_BtnLogin(lv_event_t * e);
lv_obj_t * ui_BtnLogin;
lv_obj_t * ui_Label1;
void ui_event_BtnToRegister1(lv_event_t * e);
lv_obj_t * ui_BtnToRegister1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label2;
lv_obj_t * ui_PanelLoginSuccess;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label7;
lv_obj_t * ui_PanelLoginFail;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label9;
lv_obj_t * ui_PanelLoginRepeat;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label10;


// SCREEN: ui_ScreenRegister
void ui_ScreenRegister_screen_init(void);
void ui_event_ScreenRegister(lv_event_t * e);
lv_obj_t * ui_ScreenRegister;
void ui_event_PanelReg(lv_event_t * e);
lv_obj_t * ui_PanelReg;
void ui_event_RegUser(lv_event_t * e);
lv_obj_t * ui_RegUser;
void ui_event_RegPass(lv_event_t * e);
lv_obj_t * ui_RegPass;
void ui_event_BtnSubmitReg(lv_event_t * e);
lv_obj_t * ui_BtnSubmitReg;
lv_obj_t * ui_Label4;
void ui_event_RegPassConfirm(lv_event_t * e);
lv_obj_t * ui_RegPassConfirm;
lv_obj_t * ui_Label5;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label6;
lv_obj_t * ui_KeyboardReg;
lv_obj_t * ui_PanelRegSuccess;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label11;
lv_obj_t * ui_PanelRegFail;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label12;
lv_obj_t * ui_PanelRegRepeat;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label13;


// SCREEN: ui_ScreenLobby
void ui_ScreenLobby_screen_init(void);
lv_obj_t * ui_ScreenLobby;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
void ui_event_Label14(lv_event_t * e);
lv_obj_t * ui_Label14;
lv_obj_t * ui_PanelRoomContainer;
lv_obj_t * ui_PanelRoomTemplate;
lv_obj_t * ui_LabelRoomID;
lv_obj_t * ui_LabelRoomState;
void ui_event_BtnRefresh(lv_event_t * e);
lv_obj_t * ui_BtnRefresh;
lv_obj_t * ui_Label8;
void ui_event_BtnCreateRoom(lv_event_t * e);
lv_obj_t * ui_BtnCreateRoom;
lv_obj_t * ui_awdwad;


// SCREEN: ui_ScreenGame
void ui_ScreenGame_screen_init(void);
lv_obj_t * ui_ScreenGame;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label16;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
void ui_event_Labelreadybtninfo(lv_event_t * e);
lv_obj_t * ui_Labelreadybtninfo;
lv_obj_t * ui_LabelPlayer1;
lv_obj_t * ui_LabelPlayer2;
lv_obj_t * ui_ImgTurnP1;
lv_obj_t * ui_ImgTurnP2;
lv_obj_t * ui_PanelStartTip;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label15;
lv_obj_t * ui_ImageBoard;
lv_obj_t * ui_BoardContainer;
lv_obj_t * ui_PanelMatchWin;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label18;
lv_obj_t * ui_PanelMatchLoss;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label19;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_PanelLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_InputUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardLogin,  ui_InputUser);
        _ui_flag_modify(ui_KeyboardLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_InputPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardLogin,  ui_InputPass);
        _ui_flag_modify(ui_KeyboardLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_BtnLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnLoginClicked(e);
        Texture_clean(e);
    }
}
void ui_event_BtnToRegister1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenRegister, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenRegister_screen_init);
        Texture_clean(e);
    }
}
void ui_event_ScreenRegister(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardReg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_PanelReg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardReg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_RegUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardReg,  ui_RegUser);
        _ui_flag_modify(ui_KeyboardReg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_RegPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardReg,  ui_RegPass);
        _ui_flag_modify(ui_KeyboardReg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_BtnSubmitReg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnRegisterClicked(e);
        Texture_clean(e);
    }
}
void ui_event_RegPassConfirm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardReg,  ui_RegPassConfirm);
        _ui_flag_modify(ui_KeyboardReg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLogin, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenLogin_screen_init);
        Texture_clean(e);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnLogoutClicked(e);
    }
}
void ui_event_Label14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLogin, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenLogin_screen_init);
    }
}
void ui_event_BtnRefresh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnRefreshClicked(e);
    }
}
void ui_event_BtnCreateRoom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnCreateRoomClicked(e);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnLeaveRoomClicked(e);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnReadyClicked(e);
    }
}
void ui_event_Labelreadybtninfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnReadyClicked(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenLogin_screen_init();
    ui_ScreenRegister_screen_init();
    ui_ScreenLobby_screen_init();
    ui_ScreenGame_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenLogin);
}
