// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenLogin
void ui_ScreenLogin_screen_init(void);
void ui_event_ScreenLogin(lv_event_t * e);
lv_obj_t * ui_ScreenLogin;
lv_obj_t * ui_KeyboardLogin;
lv_obj_t * ui_PanelLogin;
void ui_event_InputUser(lv_event_t * e);
lv_obj_t * ui_InputUser;
void ui_event_InputPass(lv_event_t * e);
lv_obj_t * ui_InputPass;
void ui_event_BtnLogin(lv_event_t * e);
lv_obj_t * ui_BtnLogin;
lv_obj_t * ui_Label1;
void ui_event_BtnRegister(lv_event_t * e);
lv_obj_t * ui_BtnRegister;
lv_obj_t * ui_Label3;


// SCREEN: ui_ScreenLogin1
void ui_ScreenLogin1_screen_init(void);
void ui_event_ScreenLogin1(lv_event_t * e);
lv_obj_t * ui_ScreenLogin1;
lv_obj_t * ui_KeyboardRes;
lv_obj_t * ui_PanelLogin1;
void ui_event_InputUser1(lv_event_t * e);
lv_obj_t * ui_InputUser1;
void ui_event_InputPass1(lv_event_t * e);
lv_obj_t * ui_InputPass1;
void ui_event_BtnRegister1(lv_event_t * e);
lv_obj_t * ui_BtnRegister1;
lv_obj_t * ui_Label4;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_InputUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardLogin,  ui_InputUser);
        _ui_flag_modify(ui_KeyboardLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_InputPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardLogin,  ui_InputPass);
    }
}
void ui_event_BtnLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnLoginClicked(e);
    }
}
void ui_event_BtnRegister(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnRegisterClicked(e);
    }
}
void ui_event_ScreenLogin1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_InputUser1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeyboardLogin,  ui_InputUser);
        _ui_flag_modify(ui_KeyboardLogin, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_InputPass1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardLogin,  ui_InputPass);
    }
}
void ui_event_BtnRegister1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnRegisterClicked(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenLogin_screen_init();
    ui_ScreenLogin1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenLogin);
}
