// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#ifndef _CHESS_UI_H
#define _CHESS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenLogin
void ui_ScreenLogin_screen_init(void);
void ui_event_ScreenLogin(lv_event_t * e);
extern lv_obj_t * ui_ScreenLogin;
extern lv_obj_t * ui_KeyboardLogin;
extern lv_obj_t * ui_PanelLogin;
void ui_event_InputUser(lv_event_t * e);
extern lv_obj_t * ui_InputUser;
void ui_event_InputPass(lv_event_t * e);
extern lv_obj_t * ui_InputPass;
void ui_event_BtnLogin(lv_event_t * e);
extern lv_obj_t * ui_BtnLogin;
extern lv_obj_t * ui_Label1;
void ui_event_BtnRegister(lv_event_t * e);
extern lv_obj_t * ui_BtnRegister;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_ScreenLogin1
void ui_ScreenLogin1_screen_init(void);
void ui_event_ScreenLogin1(lv_event_t * e);
extern lv_obj_t * ui_ScreenLogin1;
extern lv_obj_t * ui_KeyboardRes;
extern lv_obj_t * ui_PanelLogin1;
void ui_event_InputUser1(lv_event_t * e);
extern lv_obj_t * ui_InputUser1;
void ui_event_InputPass1(lv_event_t * e);
extern lv_obj_t * ui_InputPass1;
void ui_event_BtnRegister1(lv_event_t * e);
extern lv_obj_t * ui_BtnRegister1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
