// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#ifndef _CHESS_UI_H
#define _CHESS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenLogin
void ui_ScreenLogin_screen_init(void);
void ui_event_ScreenLogin(lv_event_t * e);
extern lv_obj_t * ui_ScreenLogin;
extern lv_obj_t * ui_KeyboardLogin;
void ui_event_PanelLogin(lv_event_t * e);
extern lv_obj_t * ui_PanelLogin;
void ui_event_InputUser(lv_event_t * e);
extern lv_obj_t * ui_InputUser;
void ui_event_InputPass(lv_event_t * e);
extern lv_obj_t * ui_InputPass;
void ui_event_BtnLogin(lv_event_t * e);
extern lv_obj_t * ui_BtnLogin;
extern lv_obj_t * ui_Label1;
void ui_event_BtnToRegister1(lv_event_t * e);
extern lv_obj_t * ui_BtnToRegister1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_PanelLoginSuccess;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_PanelLoginFail;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_PanelLoginRepeat;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label10;
// SCREEN: ui_ScreenRegister
void ui_ScreenRegister_screen_init(void);
void ui_event_ScreenRegister(lv_event_t * e);
extern lv_obj_t * ui_ScreenRegister;
void ui_event_PanelReg(lv_event_t * e);
extern lv_obj_t * ui_PanelReg;
void ui_event_RegUser(lv_event_t * e);
extern lv_obj_t * ui_RegUser;
void ui_event_RegPass(lv_event_t * e);
extern lv_obj_t * ui_RegPass;
void ui_event_BtnSubmitReg(lv_event_t * e);
extern lv_obj_t * ui_BtnSubmitReg;
extern lv_obj_t * ui_Label4;
void ui_event_RegPassConfirm(lv_event_t * e);
extern lv_obj_t * ui_RegPassConfirm;
extern lv_obj_t * ui_Label5;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_KeyboardReg;
extern lv_obj_t * ui_PanelRegSuccess;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_PanelRegFail;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_PanelRegRepeat;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label13;
// SCREEN: ui_ScreenLobby
void ui_ScreenLobby_screen_init(void);
extern lv_obj_t * ui_ScreenLobby;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Label14(lv_event_t * e);
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
