// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: chess

#include "ui.h"
#include <stdio.h>
#include <string.h>

// 必须引入我们自己的网络头文件
// 假设 ui_generated 和 network 是平级目录，所以用 ../network
#include "../network/network_client.h"

// 登录按钮点击事件
void OnLoginClicked(lv_event_t * e)
{
    // 获取输入框内容
    const char* username = lv_textarea_get_text(ui_InputUser);
    const char* password = lv_textarea_get_text(ui_InputPass);

    // 简单非空校验
    if (strlen(username) == 0 || strlen(password) == 0) {
        printf("[UI Error] Username or Password cannot be empty!\n");
        return;
    }

    // 调用网络发送
    printf("[UI] User Clicked Login: %s\n", username);
    net_send_login(username, password);
}

// 注册按钮点击事件 (新增)
void OnRegisterClicked(lv_event_t * e)
{
    // 复用登录框的输入内容
    const char* username = lv_textarea_get_text(ui_InputUser);
    const char* password = lv_textarea_get_text(ui_InputPass);

    if (strlen(username) == 0 || strlen(password) == 0) {
        printf("[UI Error] Username or Password cannot be empty!\n");
        return;
    }

    // 调用网络发送
    printf("[UI] User Clicked Register: %s\n", username);
    net_send_register(username, password);
}